### ISSUE TITLE
error on crop with joomla 3.3

### ISSUE THREAD

**Issue by ringo1963** [asikart/remoteimage#22]
hello great component!!!
i have some problems with cropping on joomla 3.3.
i get the following error on screen.
"invalid backend response. 
data ist not JSON!"

can you help me to fix this problem?
thx holger

**Comment by asika32764** [comment]
It's weird, I can't reproduce this issue in Joomla 3.3.6.

Is this issue still exists for you?

**Comment by pklinke** [comment]
Hi there,

I have the same problem in joomla 3.3.6 - but not on all sites. One site works very well (v 2.0.1) and the other with 2.01., 2.0.2 and 1.1.6 too results in this error when trying to resize an image.

Because of I like and need this component I would be happy if this issue could be resolved. If needed I can give you the login and url via personal message for testing.

Peter

**Comment by asika32764** [comment]
Could anyone provide me a site which with this error to test?

**Comment by pklinke** [comment]
yes, of course. I have setup a test-system last weekend. Here I can  create a user for you. Where shall I place url and login?

**Comment by pklinke** [comment]
Hi there,

meanwhile I have find out that this problem results in too low memory. I changed my hosting package to a higher one with more available memory. After enhancing the settings remoteimage works very well. 

![remoteimage_works_with_this_ php_setting](https://cloud.githubusercontent.com/assets/10454505/5694946/0285118c-9983-11e4-9f32-11737c8076d1.png)

**Comment by asika32764** [comment]
Thank you, I'll check whether it is caused by memory or not.

**Comment by asika32764** [comment]
Should work in [2.0.4](https://github.com/asikart/remoteimage/releases/tag/2.0.4)
